### ISSUE TITLE
403 Client Error when using MONAI Bundle helper functions

### ISSUE THREAD

**Issue by zephyrie** [Project-MONAI/model-zoo#147]
**Describe the bug**
Getting a 403 Client Error when using the MONAI Bundle commands to generate the Model Zoo page.

Error:
403 Client Error: rate limit exceeded for URL: https://api.github.com/repos/Project-MONAI/model-zoo/releases

**To Reproduce**
1. Call the MONAI Bundle "get info" functions repeatedly
2. After a certain amount of calls, it will run into the error due to rate-limiting with unauthenticated users

**Expected behavior**
We should expand these functions to allow for authentication so that users who do run into a limit can have a workaround for continuing to use the bundle info functions

**Screenshots**
![image](https://user-images.githubusercontent.com/2168510/193731822-b61baba2-d57a-4316-9e98-951117a27455.png)

**Environment**

GitHub Action environment with Ubuntu-latest and for MONAI version:

```
pip install git+https://github.com/Project-MONAI/MONAI#egg=monai
```

**Additional context**
This might not be a general issue people run into, but the way the Model Zoo page was being generated, it used various helper functions to make it easier to pull the required info.  The issue seems to be that many of the helper functions call out to `_get_all_bundles_info`, which makes a request to https://api.github.com/repos/Project-MONAI/model-zoo/releases.  After a certain number of calls, the functions will all fail since it's been rate-limited.  

I've re-structured the Model Zoo pages to not run into these issues anymore, but it might be helpful to add a way to add an authentication key that will expand the rate limit.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help confirm and fix it? Seems like an issue.

Thanks in advance.

**Comment by yiheng-wang-nv** [comment]
Thanks @zephyrie , I checked the official doc about the rate limits (https://docs.github.com/en/rest/overview/resources-in-the-rest-api#oauth2-token-sent-in-a-header), it's good to add the authentication option within the helper functions.
I will create a PR in MONAI repo to address it.
