### ISSUE TITLE
Display name for Models in metadata JSON

### ISSUE THREAD

**Issue by zephyrie** [Project-MONAI/model-zoo#148]
**Is your feature request related to a problem? Please describe.**
A display or "pretty" name for each Model in the metadata.json and adding a requirement that all future models also need a display name.

**Describe the solution you'd like**
Add display names to each of the current MONAI Models metadata JSON so that we have the preferred name being displayed in the Model Zoo.

**Describe alternatives you've considered**
Creating a regex/replace function that replaces keywords like MRI, CT, NIST, UNETR, etc. within the current bundle names.  However, this would require customization as the Model Zoo continued to expand.

**Additional context**
Right now, when generating the Model Zoo page, the names being used are the bundle name with the first letter capitalized.  It would be better to have a proper display name that is a concise name used when generating the page.  That way, we have proper formatting for things like MRI or UNETR.

Example:
![image](https://user-images.githubusercontent.com/2168510/193732961-83978b63-7f89-4923-aa3e-98bb626028f0.png)

**Comment by ericspod** [comment]
For some of the models we can use title case and figure out some acronyms but in general a "title" tag in the metadata would help here.

**Comment by yiheng-wang-nv** [comment]
Hi @Nic-Ma @wyli @daguangxu , I think add an optional "title" tag within the metadata is a good choice as @ericspod suggested. It is helpful for showing our bundles in the webpage. Could we arrange a quick meeting to discuss it? Thanks!

**Comment by Nic-Ma** [comment]
Maybe let's add a field "name" in the `metadata.json`?

Thanks.

**Comment by wyli** [comment]
thanks, optional 'name' sounds good to me as well...

**Comment by yiheng-wang-nv** [comment]
Update: I will add the new tag for current bundles, and using the same name first in default.

**Comment by yiheng-wang-nv** [comment]
> Update: I will add the new tag for current bundles, and using the same name first in default.

I discussed with @zephyrie , and for the default name for `name` tag, we should remove `_` on the bundle folders, and capitalize the name. In addition, some of the names should be changed. For example, `Brats` should be `BraTS`.
