### ISSUE TITLE
Mismatch for UNETR FLOPs between UNesT and UNETR papers

### ISSUE THREAD

**Issue by AbdelrahmanShakerYousef** [Project-MONAI/model-zoo#164]
Hello, I have a question please regarding your UNesT paper: https://arxiv.org/pdf/2209.14378.pdf

In Table 2, you mentioned that for an input size of 96x96x96 UNETR has params of 92.6M and FLOPs of 268.0G. However, in UNETR paper in Table 5, the authors mentioned that the number of params is 92.6M but the FLOPs are 41.19G, with the same input size of 96x96x96. Could you please clarify that?

Thanks!

**Comment by Nic-Ma** [comment]
Hi @tangy5 ,

Could you please help share some details here?

Thanks in advance.

**Comment by tangy5** [comment]
Hi @AbdelrahmanShakerYousef , thanks for the question, very appreciative for the interest of the UNesT work. I can provide details on how the numbers are got in the UNesT, the  number showed in UNesT are not taken directly from other papers such as UNETR. We measured all independently and under exact same experiment setting in evaluating the whole brain segmentation data. All numbers in UNesT are acquired by using this OpCounter: https://github.com/Lyken17/pytorch-OpCounter, I would suggest to calculate your FLOPS, MACS locally under the specific experiment setting, number can be different in variants.  Note the macs and FLOPS are different, and. having relative FLOPS = 2MACS(roughly equivalent, especially variant models). 
Thanks, hope this helps and can assist for getting your experiment FLOPS.

**Comment by AbdelrahmanShakerYousef** [comment]
Thank you @tangy5 for clarification, but what do you mean by "evaluating the whole brain segmentation data"?

Isn't it just the FLOPs for a single input volume of 96 × 96 × 96 ?

**Comment by tangy5** [comment]
> Thank you @tangy5 for clarification, but what do you mean by "evaluating the whole brain segmentation data"?
> 
> Isn't it just the FLOPs for a single input volume of 96 × 96 × 96 ?

It is calculated with tensor input: [1,1,96,96,96], the FLOPS should only relate to input size, models. The whole brain segmentation data means the FLOPS are got from our practice. Thanks.
