### ISSUE TITLE
Check license of `breast_density_classification` bundle

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#170]
Hi @vikashg , the initial PR of your bundle has just been merged, thanks for the contribution. Recently, we made some changes of the license format, and each bundle may include two license files: one for the bundle itself, the other is for the related dataset (optional).
Since the changes happened after you finished the main part of the bundle, I thought put a new PR to address this issue is more clear.

The new license format is shown in: https://github.com/Project-MONAI/model-zoo#license   and for your bundle, I found an apache license file [here](https://github.com/Project-MONAI/model-zoo/blob/8e0f7c5f06f22b604d4f920b062696e682e8f099/models/breast_density_classification/docs/license.txt). Could you confirm that the bundle itself (include config files and weights) follows the apache license? In addition, is there any data related license that are needed? I'm not sure if the sample data you included need to meet any license, could you please help to confirm it too?

After confirming the license part, I will submit a PR to address them and invite you to review it, thanks!

**Comment by vikashg** [comment]
HI @yiheng-wang-nv. I added the apache license as was instructed in the contributions section. Do I need to change it? Yes I can confirm that the bundle follows the apache license " that software for any purpose, to distribute it, to modify it, and to distribute modified versions of the software under the terms of the license, without concern for royalties" 
The data contained is just JPEG images so they do not have any patient data and there are no licensing concerns. 
Hope this answers your question ?

**Comment by vikashg** [comment]
Another question @yiheng-wang-nv  Do I need to "build" the documentation so it shows up on the webpage ?

**Comment by yiheng-wang-nv** [comment]
Hi @vikashg , @zephyrie helps to show the doc on the webpage, and the content is extracted from your bundle's metadata and readme files. Therefore, if you'd like to supplement more information, you just need to update these two files.

As for the license part, thanks for the explain, and I will submit a PR to address them.
