### ISSUE TITLE
Update Bundles to use MONAI 1.0.1 and pytorch 1.13.0

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#180]
The following bundles need to be updated into using MONAI 1.0.1 and Pytorch 1.13.0:
`brats_mri_segmentation` @yiheng-wang-nv 
`lung_nodule_ct_detection` @Can-Zhao 
`pancreas_ct_dints_segmentation` @dongyang0122 
`pathology_tumor_detection` @drbeh 
`spleen_ct_segmentation` @yiheng-wang-nv  (cannot find yufan's account, I already checked it)
`spleen_deepedit_annotation` @diazandr3s 
`swin_unetr_btcv_segmentation` @tangy5 
`endoscopic_inbody_classification` and `endoscopic_tool_segmentation` @binliunls 

May need your help to check if `monai==1.0.1` and `torch==1.13.0` work on your bundle, if it works, I can help to update the bundle directly, and if some other places (such as transforms) also need to be changed, may need your help to submit a PR. Thanks!

**Comment by tangy5** [comment]
Hi @yiheng-wang-nv , let me use this issue for the changes so that we won't bother too many tickets. 
Swin Unetr bundle should be good with monai 1.0.1 and pytorch 1.13.0. Some updates here: https://github.com/Project-MONAI/model-zoo/pull/182
Thanks.

**Comment by binliunls** [comment]
Hi @yiheng-wang-nv ,
      I have run endoscopic_inbody_classification and endoscopic_tool_segmentation bundles. They work fine with monai 1.0.1 and pytorch 1.13.0.
Thanks,
Bin
