### ISSUE TITLE
Missing files in the pathology bundle

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/model-zoo#185]
**Describe the bug**
I read the README doc of Pathology bundle and it says something about  “configs/environment.json” and “prepare_inference_data.sh”:
https://github.com/Project-MONAI/model-zoo/tree/dev/models/pathology_tumor_detection#data-preparation
But actually I didn’t find these 2 files in the configs of the bundle.

**Comment by yiheng-wang-nv** [comment]
Hi @drbeh , I think this ticket can be resolved with monai 1.0.1 and torch 1.13.0 together (as mentioned in #180 ), thanks in advance!

**Comment by yiheng-wang-nv** [comment]
> Hi @drbeh , I think this ticket can be resolved with monai 1.0.1 and torch 1.13.0 together (as mentioned in #180 ), thanks in advance!

This part has been resolved in https://github.com/Project-MONAI/model-zoo/pull/187 thus just need to figure out the 2 missing files.

Another thing that need to be addressed is that there are some "MMAR" related descriptions in the readme file, may need @drbeh 's help to correct them, thanks in advance!
