### ISSUE TITLE
404 error of link in `endoscopic_inbody_classification` bundle

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#186]
The link of 20 samples for the bundle seems failed

https://drive.google.com/uc?id=1rQQfHcZFs74OG0uJsL4vg7YqMWXV-s4k

**Comment by yiheng-wang-nv** [comment]
Hi @binliunls  may need your help to double confirm it, thanks in advance!

**Comment by binliunls** [comment]
Hi @yiheng-wang-nv ，
     Thank you for your feedback. The samples have been uploaded to monai and the link is shown below.
     https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/inbody_outbody_samples.zip
Thanks,
Bin
