### ISSUE TITLE
requires either `network` or `network_def` but not both?

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/model-zoo#209]
**Is your feature request related to a problem? Please describe.**
the requirements are both `network` and `network_def` keys:

https://github.com/Project-MONAI/model-zoo/blob/c4752051e315917089f098651e13776bac92630b/ci/verify_bundle.py#L30-L31

I think the contents for these keys are duplicated, perhaps we can make  `network_def` optional

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Do you have any proposal idea to simplify the config? For example:
```json
{
    "network_def": {
        "_target_": "UNet",
        "spatial_dims": 3,
        "in_channels": 1,
        "out_channels": 2
    },
    "network": "$@network_def.to(@device)"
}
```

Thanks.

**Comment by Nic-Ma** [comment]
Hi @SachidanandAlle ,

I think the initial requirements of these 2 keys is from MONAI Label, but I see you changed the const strings now.
Do you still need both the 2 keys existing in a bundle?

Thanks in advance.

**Comment by SachidanandAlle** [comment]
I don't think monailabel had this requirement.. @tangy5 can you double check.. we can live with one..

**Comment by tangy5** [comment]
MONAI Label made changes according to bundle network definitions, now uses both two. But I think we can use one key instead.

If we merge the two keys together, we can change to left one in MONAI Label.

https://github.com/Project-MONAI/MONAILabel/blob/9a37fab1abe8a9374505e9e0e174f88cbd3a0897/monailabel/tasks/infer/bundle.py#L49

https://github.com/Project-MONAI/MONAILabel/blob/9a37fab1abe8a9374505e9e0e174f88cbd3a0897/monailabel/tasks/train/bundle.py#L49

**Comment by wyli** [comment]
sure, I think we can make it simple and consistent, and use `network_def` only, I'll make the change to remove the requirement for `network` in the model zoo.

**Comment by tangy5** [comment]
> sure, I think we can make it simple and consistent, and use `network_def` only, I'll make the change to remove the requirement for `network` in the model zoo.

Sure, let me know if this is merged, we need to make changes to MONAI Label and have some tests. 

Thank you!

**Comment by tangy5** [comment]
HI @wyli, one question, if we remove key "network", will all bundles need to update accordingly?

**Comment by wyli** [comment]
I don't think so @tangy5, we just don't assume there's `network` key when work with the bundles, and new bundles may not contain this key.

**Comment by wyli** [comment]
Please help update monailabel to only requires the 'network_def' 
@tangy5 

I think preferably monailabel raises a warning for bundles that has 'network' but not 'network_def' instead of an exception for the upcoming versions
