### ISSUE TITLE
Add an option to run inference based on torchscript weights in model.ts

### ISSUE THREAD

**Issue by myron** [Project-MONAI/model-zoo#231]
Add an option to run inference based on torchscript weights model.ts

Currently it's always using model.pt weights

**Comment by Nic-Ma** [comment]
Example steps:
1. Remove or disable the `CheckpointLoader`.
2. Change the `network_def` to `"network_def": "$torch.jit.load(<your own path>)"`.

Thanks.

**Comment by yiheng-wang-nv** [comment]
Hi @myron and @Nic-Ma , could I double confirm that which place should be updated to add this option? In a bundle, or in all (internal contributed) bundles?

**Comment by myron** [comment]
probably it makes more sense to do it in bundle, since we need it for all bundles.. but I'm not sure how difficult it is

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

I would suggest to add some description in this section of the doc:
https://github.com/Project-MONAI/model-zoo/blob/dev/CONTRIBUTING.md#verify-torchscript
Then developer or user will know how to quickly modify a bundle to test with the TorchScript model.
@myron What do you think?

Thanks in advance.

**Comment by myron** [comment]
okay, sure, it will be helpful, may be later we can think of a more elegant way

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Please update the contributing.md for it.

Thanks.
