### ISSUE TITLE
Call `run_premerge_gpu.sh` from `run_premerge_cpu.sh`

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#234]
Is it possible to run cpu based blossom ci test first, and call gpu based blossom ci test if necessary? 
It will reduce the usage of gpu and save some time when gpu resources are not available.

**Comment by yiheng-wang-nv** [comment]
Hi @YanxuanLiu , may need your help here to address this feature request, thanks!

**Comment by wyli** [comment]
might be useful to regularly run all tests as well.

currently, unchanged bundles are never tested any more after merging into dev
https://github.com/Project-MONAI/model-zoo/blob/94673ac426edbc2d1953ecd1d5c15052c56d2598/ci/run_premerge_gpu.sh#L76

**Comment by yiheng-wang-nv** [comment]
According to @YanxuanLiu 's suggestion, I will create a PR to address:
1. avoid running blossom ci for PRs that are created by `update_model_info.py` (these PRs only change the `models/model_info.json` and do not need to do the tests)
2. modify `verify_bundle.py` and add `verify_data_shape` into "min" mode (it does need to use gpu)
cc @wyli

**Comment by yiheng-wang-nv** [comment]
> might be useful to regularly run all tests as well.
> 
> currently, unchanged bundles are never tested any more after merging into dev
> 
> https://github.com/Project-MONAI/model-zoo/blob/94673ac426edbc2d1953ecd1d5c15052c56d2598/ci/run_premerge_gpu.sh#L76

Hi @wyli , for this issue, could we create a new ticket? I think it needs to add a new workflow and run periodically. It also needs to change the `verify_bundle.py` and disable some verifications such as `verify_version_changes` (which requires to recognize a new version number).

**Comment by wyli** [comment]
thanks I've created a ticket https://github.com/Project-MONAI/model-zoo/issues/249, and I realised maybe that tests should be done with the zipped bundle file (from https://github.com/Project-MONAI/model-zoo/releases/tag/hosting_storage_v1) instead of `dev` itself because the contributors may or may not make the large files available forever..
