### ISSUE TITLE
Set bundle_root to current directory by default

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/model-zoo#247]
**Is your feature request related to a problem? Please describe.**
It's easy to misconfigure the bundle root when copying bundle files around. I would suggest to use `"bundle_root": "$os.getcwd()"`.
Then issues like #144 could be avoided.

**Describe the solution you'd like**
Set bundle_root in all models to `"bundle_root": "$os.getcwd()"` by default.

**Describe alternatives you've considered**
Current hard-coded paths for bundle_root can cause confusion and might be unexpected to have to configure for users.

**Additional context**
Tested spleen_ct_segmentation with `"bundle_root": "$os.getcwd()"` and it seems working as expected.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

What do you think about it?

Thanks.

**Comment by wyli** [comment]
I think putting a good default value makes sense... Also the device default could be cuda0 if has cuda else cpu0?

**Comment by yiheng-wang-nv** [comment]
Thanks @holgerroth . Hi @Nic-Ma and @wyli , how about address this ticket after this release?

**Comment by holgerroth** [comment]
Sure. This is not urgent.

**Comment by SachidanandAlle** [comment]
Sometimes user might not be in the same directory.  When people use bundles programmatically, there is a higher chance of such situation where user is invoking the scripts from a different user directory.

I think It's ok to have invalid directory than unknown directory.
Especially when the script allows to run python statements through json files.  Atleast user will know that he/she has to fix the path for bundleroot instead of seeing something messed up in his/her current working directory.

**Comment by SachidanandAlle** [comment]
Also we never have valid train/validation dataset values correctly configured in these scripts..

**Comment by holgerroth** [comment]
> 

If one follows the instructions, e.g. here for spleen_ct_segmentation bundle, then they already assume the user being inside the bundle root folder itself 
```
python -m monai.bundle run training --meta_file configs/metadata.json --config_file configs/train.json --logging_file configs/logging.conf
```
So, the current user directory shouldn't be messed up but output files will be added only the bundle folder - which makes sense to me. We are only talking about the default behavior. For other programmatic uses of bundle, you would probably have to change the bundle_root anyhow as we do for example in [MonaiAlgo](https://github.com/Project-MONAI/MONAI/blob/e15da1ca3f0651faf3bc75c8274f417acc2c27b1/monai/fl/client/monai_algo.py#L165)

**Comment by yiheng-wang-nv** [comment]
Hi @SachidanandAlle , here I wish to follow up with this ticket. What do you think of @holgerroth 's suggestion? I agree that for default value, we can unify to use current directory (at least for bundles contributed by MONAI teams) for convenience (users do not need to modify too much things when running the example commands).

**Comment by SachidanandAlle** [comment]
Yes.. we can go ahead and make the changes as @holgerroth suggested.  I have verified it to be working for some bundles.
