### ISSUE TITLE
regular tests for existing models

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/model-zoo#249]
**Is your feature request related to a problem? Please describe.**
existing bundles will never be tested again once merged into `dev` and deployed.

it would be helpful to test the zipped files regularly by downloading and checking the bundles from here:
https://github.com/Project-MONAI/model-zoo/releases/tag/hosting_storage_v1

**Comment by yiheng-wang-nv** [comment]
I'd like to address this feature request. I will build regular tests for all bundles that have the latest versions from: https://github.com/Project-MONAI/model-zoo/releases/tag/hosting_storage_v1 and check if they can meet our latest ci tests.
