### ISSUE TITLE
Loadable Parameter for Visualization

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/model-zoo#308]
Hi Team, one thing it might of interest to discuss in the bundle config files. 

As more and more bundles are made and will support to MONAI Label, Deploy, etc....
I'm thinking if we can define a standard key for "loadable parameters" that can be loaded by other frameworks such as Label/Deploy for visualization. 

For example, we can define a key "loadable_params" that include potential parameters for visualization in Slicer UI.

```
    "loadable_params": [
        "highres",
        "sw_overlap",
        "sw_batch_size"
    ],

```
See the three config parameters can be loaded in 3D Slicer plugin 
Label can load those keys and parse the value for users can control in the Slicer plugin/other viewers. 

![options2](https://user-images.githubusercontent.com/58751975/218187804-e923aefe-7bc6-4ad6-b81d-135dac950141.png)

All we need is a standard name for these loadable parmaters list.

Any suggestions?

**Comment by Nic-Ma** [comment]
Hi @tangy5 ,

Do all these parameters come from the `inferer` part?

Thanks.

**Comment by wyli** [comment]
the name 'loadable' is a bit confusing to me, will there be parameters that we not loadable?

**Comment by tangy5** [comment]
Not all parameters come from "inferer", we would like to expose some parameter to show in MONAI Label config options. 

how about "displayable_configs"?

Let me think about this.

**Comment by tangy5** [comment]
I'm using a name "displayable_configs" that can be read into MONAI Label config and display to viewers such as 3D Slicer.

Thanks for all the suggestions. Close for now.
