### ISSUE TITLE
add default meta/logging file inputs

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/model-zoo#319]
**Is your feature request related to a problem? Please describe.**
```
--meta_file configs/metadata.json --logging_file configs/logging.conf
```

this is used extensively in the bundle CLI, would be great to make these options enabled by default, to simplify the CLI usage

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

I think you can add the default args in the bundle script `run` of MONAI core.
Then after MONAI 1.2 released, let's update all the model-zoo bundles.

Thanks.

**Comment by yiheng-wang-nv** [comment]
Thanks @wyli and @Nic-Ma .
I will add the default args soon, and in the bundle side, according to: https://github.com/Project-MONAI/MONAI/pull/6051
I will update all bundles after MONAI 1.2 is released
