### ISSUE TITLE
wholeBody_ct_segmentation model not available for MONAI-Label

### ISSUE THREAD

**Issue by nvahmadi** [Project-MONAI/model-zoo#320]
**Describe the bug**
Just tried using the wholeBody_ct_segmentation_v0.1.0 model with MONAI-Label, as it is shown in the ["MONAI Label Showcare"](https://github.com/Project-MONAI/model-zoo/tree/dev/models/wholeBody_ct_segmentation#monai-label-showcase). 

**To Reproduce**
1. Pull and run latest docker image `projectmonai/monailabel:latest`
2. Inside container, download the latest monaibundle app via `monailabel apps --download --name monaibundle --output /data/Projects/MONAI-label/apps/v0.6.0`
3. Start MONAI-Label server, e.g. via
```
monailabel start_server \
   --app /data/Projects/MONAI-label/apps/v0.6.0/monaibundle \
   --studies /data/Projects/MONAI-label/datasets/pancreas_test \
   --conf models wholeBody_ct_segmentation
```

**Expected behavior**
Expected MONAI-Label to auto-download the model from Model Zoo, and startup monailabel server.

**Actual behavior**
MONAI-Label server returns an error, it seems that the model is not yet registered or compatible with MONAI-Label, see error message below. This is independent whether I use the model identifier `wholeBody_ct_segmentation` or `wholeBody_ct_segmentation_v0.1.0`. Would be great if this worked OOTB, or if documentation in the "MONAI Label Showcase" detailed how to run this model.
```
Invalid Model(s) are provided: ['wholeBody_ct_segmentation'], either not in model zoo or not supported with MONAI Label
Following are the available models.  You can pass comma (,) separated names to pass multiple
Available bundle with latest tags:
   -c models
        lung_nodule_ct_detection
        pancreas_ct_dints_segmentation
        prostate_mri_anatomy
        renalStructures_UNEST_segmentation
        spleen_ct_segmentation
        spleen_deepedit_annotation
        swin_unetr_btcv_segmentation
        wholeBrainSeg_Large_UNEST_segmentation
``` 

**Environment**
* Latest docker image `projectmonai/monailabel:latest`. 
* MONAI v1.1.0
* monailabel 0+untagged.1.g40fd783.dirty

**Comment by tangy5** [comment]
The bundle is just merged, there will be some modifications on the MONAI Label side to enable this bundle use in Slicer. Will soon be enabled, will update us.

**Comment by nvahmadi** [comment]
I see, thanks a lot and no pressure :) I mis-understood the screenshot and thought it was already available. Looking forward to trying this!
