### ISSUE TITLE
Enhance CI tests for TensorRT supported bundles

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#326]
Currently, all bundles use the same pipeline to do pre-merge tests. For each changed bundle (within a pull request), its required libs (such as MONAI version, Torch version, ...) will be extracted from `metadata.json`, and installed with `pipenv` during the testing workflow.

However, to enable TensorRT for a part of bundles (see also: https://github.com/Project-MONAI/model-zoo/issues/324), we need to add related tests. Install TensorRT requires more works than `pipenv install`, thus we decided to use a MONAI docker container (https://docs.monai.io/en/latest/installation.html#from-dockerhub) to do the test.

A limitation is that we need to align the libs (versions) used for all TensorRT supported bundles. As the first stage, three bundles will support TensorRT (see also: https://github.com/Project-MONAI/model-zoo/pull/325), and they will unify MONAI and Torch versions.

The expected new CI tests logic is like:

<img width="1017" alt="Screen Shot 2023-03-15 at 10 56 53 AM" src="https://user-images.githubusercontent.com/68361391/225193559-9b92a9e0-9401-43cc-a898-26617e54b9a8.png">

As shown in the figure, we will support two kinds of tests:

1. For each pull request, if a TensorRT supported bundle is changed, it will trigger a corresponding TensorRT test within MONAI docker container (latest LTS version).
2. Periodically (such as weekly) TensorRT tests will be executed on all supported bundles.

**Comment by yiheng-wang-nv** [comment]
@YanxuanLiu will help to build the new pipeline, and I will prepare the new test scripts.

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv @YanxuanLiu ,

In my simple mind, I think for the first step we can enable weekly CI job to run it on dev branch or some specific branch.
For the TensorRT environment, let's stick with the released docker of latest MONAI **LTS version**.
What do you think?
CC @wyli .

Thanks.

**Comment by yiheng-wang-nv** [comment]
> Hi @yiheng-wang-nv @YanxuanLiu ,
> 
> In my simple mind, I think for the first step we can enable weekly CI job to run it on dev branch or some specific branch. For the TensorRT environment, let's stick with the released docker of latest MONAI **LTS version**. What do you think? CC @wyli .
> 
> Thanks.

Hi @Nic-Ma , 

> In my simple mind, I think for the first step we can enable weekly CI job to run it on dev branch or some specific branch

Here do you mean use dev branch to test all TensorRT bundles? Yes, I think we can maintain all these bundles to work with latest MONAI dev branch.

> For the TensorRT environment, let's stick with the released docker

Agree.

**Comment by Nic-Ma** [comment]
I mean use the latest **MONAI LTS version** docker to run the **dev branch of this repo**.

Thanks.
