### ISSUE TITLE
Enable `/black` in comments

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#34]
Same as MONAI repo, it will be more convenient for users to fix code format issues

**Comment by yiheng-wang-nv** [comment]
Issue: https://github.com/Project-MONAI/monai-code-formatter/runs/6911719251?check_suite_focus=true#step:7:336
Since `runtests.sh` in this repo does not have `clangformat` check, we cannot use `project-monai/monai-code-formatter` directly in `chatops.yml`.

**Comment by wyli** [comment]
addressed by updating the code formatter logic. https://github.com/Project-MONAI/monai-code-formatter/actions/runs/2926956836
