### ISSUE TITLE
Mismatch val score on `swin_unetr_btcv_segmentation`

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#340]
When I worked on #294 , I found that the achieved val score based on provided weights is around 0.8120 which is different from the readme and metadata.json ( 0.8269).
Hi @tangy5 , may need your help to double confirm the value which comes from: https://github.com/Project-MONAI/model-zoo/pull/204/files#diff-15aa4c2cd1b45d72fe9283eca4c9af116a0dd5e17d6428f0a339f9ce65e2ffd8R50

**Comment by tangy5** [comment]
The readme and metadata json need update, commit the changes direct to the PR. https://github.com/Project-MONAI/model-zoo/pull/339
Thanks for figuring out.
