### ISSUE TITLE
Adding premerge ci tests

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#39]
We can enable the following ci tests for a pull request if it changes (adds) a bundle:

1. If `large_files` file exists, check the download link and checksum for each large file.
2. Verify the metadata format.
3. Verify the data shape of network.
4. Check TorchScript export, if the bundle supports.

**Comment by yiheng-wang-nv** [comment]
Hi @YanxuanLiu , FYI. I am working on this ticket, and it may need your help to enable the tests into blossom, thanks in advance.

**Comment by YanxuanLiu** [comment]
I'm going to create two interface scripts in model-zoo repo, just like we did for NVFlare: https://github.com/NVIDIA/NVFlare/tree/dev/ci<br>
Jenkinsfile will execute these two scripts to run GPU tests and non-GPU tests seperately. It means we only need to modify the interface scripts when you want to update the tests, and we don't need to do any changes to Jenkinsfile.<br>
