### ISSUE TITLE
Add RAM used for Bundles that use CacheDataset

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#395]
Some of the bundles use CacheDataset, but do not provide any information on how many RAM are required. For a large dataset, caching all data need large RAM otherwise error will be raised. It would be hard to debug when meeting this kind of error because the error message is not informative, for example:
```
8.72s/it]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1332 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 1331) of binary: /usr/bin/python
```

Therefore, I think we should add related information in README, and provide some suggestions for users that do not have enough RAM.

**Comment by yiheng-wang-nv** [comment]
Related bundles include:

1. pathology_nuclei_classification @KumoLiu 
1. pathology_nuclei_segmentation_classification @KumoLiu 
1. endoscopic_tool_segmentation @binliunls 
1. spleen_ct_segmentation @heyufan1995 
1. spleen_deepedit_annotation @tangy5 
1. swin_unetr_btcv_segmentation @tangy5 
1. pathology_nuclick_annotation @tangy5 
1. wholeBody_ct_segmentation @tangy5 
1. pancreas_ct_dints_segmentation @dongyang0122 

May need your help to supplement the information of how many RAM is required to run the bundle training with default settings (cache rate). I personally think that it is helpful especially for bundles that train on large dataset.

For bundles that use different cache rate in `multi_gpu_train.json` and `train.json`, I think we should unify the settings to avoid complex explanations.

**Comment by yiheng-wang-nv** [comment]
To sum up according to discussions as well as @zephyrie 's comments in PR: #406 #399 , I think we need to add two sections into README:

**1. (optional)  The template is like:**

### Memory Consumption

- Dataset Manager: CacheDataset
- Data Size:
- Cache Rate:
- Single GPU - System RAM Usage:
- Multi GPU (8 GPUs) - System RAM Usage:

**2. (necessary on bundles use CacheDataset) The template is like:**

### Memory Consumption Warning

If you face memory issues with CacheDataset, you can either switch to a regular Dataset class or lower the caching rate cache_rate in the configurations within range $(0, 1)$ to minimize the System RAM requirements.

Hi @zephyrie @Nic-Ma @daguangxu @dongyang0122 @tangy5 what do you think?

**Comment by zephyrie** [comment]
That looks good! My only suggestion is to have the number of GPUs in the parenthesis.  E.g. "Multi GPU (8 GPUs)".

Also, I'll also update our best template to include this section.

**Comment by dongyang0122** [comment]
The template is well-structured and suitable.
