### ISSUE TITLE
What's the correct segmentation label match the organ name in Wholebody ct segmentation pre-trained model?

### ISSUE THREAD

**Issue by ytl0623** [Project-MONAI/model-zoo#396]
Hi, I used to execute inference with Wholebody ct segmentation from monai model zoo.

But after I finished the process the output image is NOT match the organ list (like picture below).

The organ list (I supposed) is sort by A-Z, but the real output image is red text. 
![image](https://user-images.githubusercontent.com/55120101/234781625-6c57583b-cc07-4d4e-ba5d-341e1f7d103f.png)

So, what is the correct organ list with Wholebody ct segmentation model, and where can I find it?

Thanks!

**Comment by tangy5** [comment]
Thanks for reporting, this list follows the order of TotalSegmentator dataset. We will look into the order and see if they are properly set.

**Comment by tangy5** [comment]
Hi @ytl0623 , how do you get the above screen shot's list? 

If you are looking for a organ list, it's here: https://github.com/Project-MONAI/model-zoo/blob/dev/models/wholeBody_ct_segmentation/configs/metadata.json

I checked in 3D Slicer, the list is not sorted in A-Z, and the organ names should be correct. 

Let us know if this list is not correctly working in other viewers.
