### ISSUE TITLE
Error using inference in `Endoscopic tool segmentation` model

### ISSUE THREAD

**Issue by IvanHCenalmor** [Project-MONAI/model-zoo#401]
**Describe the bug**
I was testing the inference in the `Endoscopic tool segmentation` model (https://github.com/Project-MONAI/model-zoo/tree/05357dcdddaf2560de1ec62ea382c83bf1e82c1f/models/endoscopic_inbody_classification) and I received the following errors:

```
...
TypeError: __init__() got an unexpected keyword argument 'pre_conv'
...
RuntimeError: Failed to instantiate 'monai.networks.nets.flexible_unet.FlexibleUNet' with kwargs: {'in_channels': 3, 'out_channels': 2, 'backbone': 'efficientnet-b2', 'spatial_dims': 2, 'pretrained': False, 'is_pad': False, 'pre_conv': None}
...
```

After lookinf at the `inference.json` I notice that the problem was in the networks definition, where the `pre_conv` argument is passed to the `FlexibleUNet` class and I imagine that it does not receive that argument.

```
...
    "network_def": {
        "_target_": "FlexibleUNet",
        "in_channels": 3,
        "out_channels": 2,
        "backbone": "efficientnet-b2",
        "spatial_dims": 2,
        "pretrained": false,
        "is_pad": false,
        "pre_conv": null  <---------- THIS ARGUMENT ----------
    },
...
```

I do not know if `FlexibleUNet` should receive that argument or if the `inference.json` should be changed, but it was just for you to known that this model with the actual configuration does not run.

**To Reproduce**
1. Go to https://github.com/Project-MONAI/model-zoo/tree/05357dcdddaf2560de1ec62ea382c83bf1e82c1f/models/endoscopic_inbody_classification
2. Download the model and install the MONAI Python library
3. Run commands 'python -m monai.bundle run --config_file configs/inference.json' 

**Expected behavior**
In my case I was only testing, I am more interested in the model than in using the inference, and at  least I was expecting to be able to load the model.

**Environment**
```
================================
Printing MONAI config...
================================
MONAI version: 1.1.0
Numpy version: 1.23.5
Pytorch version: 1.13.1+cu117
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI __file__:  .../anaconda3/envs/monai/lib/python3.9/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 5.1.0
scikit-image version: 0.20.0
Pillow version: 9.5.0
Tensorboard version: 2.12.1
gdown version: 4.7.1
TorchVision version: 0.14.1+cu117
tqdm version: 4.65.0
lmdb version: 1.4.0
psutil version: 5.9.0
pandas version: 2.0.0
einops version: 0.6.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 2.2.2
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.6 LTS
Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.31
Processor: x86_64
Machine: x86_64
Python version: 3.9.16
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 4
Num logical CPUs: 8
Num usable CPUs: 8
CPU usage (%): [31.4, 19.4, 20.7, 30.2, 30.4, 19.5, 18.5, 31.8]
CPU freq. (MHz): 2
Load avg. in last 1, 5, 15 mins (%): [20.8, 21.9, 23.4]
Disk usage (%): 83.6
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 5.7
Available memory (GB): 1.2
Used memory (GB): 4.2

================================
Printing GPU config...
================================
Num GPUs: 0
Has CUDA: False
cuDNN enabled: True
cuDNN version: 8500

```

**Comment by binliunls** [comment]
Hi @IvanHCenalmor ,
     The endoscopic_tool_segmentation bundle has a breaking change in MONAI 1.2.0. This `pre_conv` parameter is added to the bundle since then. I saw you were using MONAI 1.1.0. Here are some suggestions for solving this issue:

1. Simply remove the `pre_conv` parameter from the config file or use a lower version of this bundle like `0.4.1`. 
2. Upgrade MONAI to the 1.2.0 (now it is in rc5 version), [here](https://hub.docker.com/r/projectmonai/monai/tags) is the link of images.

Thanks,
Bin

**Comment by yiheng-wang-nv** [comment]
Close this ticket as the issue should be fixed according to @binliunls 's method. Feel free to reopen it if there have the issue.
