### ISSUE TITLE
Unify required properties in bundles

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#437]
`monai.bundle.properties` in this PR: https://github.com/Project-MONAI/MONAI/pull/6432 defines the new requirements of bundles.
However, it has some differences of what we were defined in: https://github.com/Project-MONAI/model-zoo/blob/b72b9fbe80e999407d4d136207778a02f37d3c6d/CONTRIBUTING.md#preferred-files-and-keys

Especially for `InferProperties` which is for inference and evaluate config files. In current model zoo bundles, contributors usually include `train.json` and just override some components to build the `evaluate.json` ([example](https://github.com/Project-MONAI/model-zoo/blob/b72b9fbe80e999407d4d136207778a02f37d3c6d/models/brats_mri_segmentation/configs/evaluate.json)). It conflicting to properties like "dataset", "dataset_data" and so on.

**Comment by Nic-Ma** [comment]
Please use `TrainProperties` to verify.

Thanks.
