### ISSUE TITLE
document the PR commands

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/model-zoo#461]
**Is your feature request related to a problem? Please describe.**
would be great to clarify that all contributors can trigger the auto formatting pipeline by commenting `/black` (if `Maintainers are allowed to edit this pull request.` is not disabled)

and the maintainers can trigger integration tests by commenting `/build`

**Comment by yiheng-wang-nv** [comment]
Thanks @wyli .
MONAI Repo has a good reference:
https://github.com/Project-MONAI/MONAI/blob/60620e46645d131f3fe05e98f4c91e1fbda9bf13/CONTRIBUTING.md?plain=1#L334
I will submit a PR to address it.
