### ISSUE TITLE
Rotation of output images in prostate_mri_anatomy

### ISSUE THREAD

**Issue by FaresAlMohamad** [Project-MONAI/model-zoo#481]
This problem is about the inference.json config file for the prostate_mri_anatomy model. The transformations applied to the test data during preprocessing are not reversed during postprocessing; thus, the resulting predictions have a different rotation compared to the original images and labels. I would like to add an invertd() function to postprocessing.

Additionally, running the inference on a PC without a GPU leads to an error because the handlers function 'CheckpointLoader' attempts to load the model to the GPU. I want to add a parameter that loads the model to the CPU when the GPU is unavailable.

**Comment by yiheng-wang-nv** [comment]
Thanks for posting this issue, the enhancements will be helpful. Welcome to contribute the updates, and if you meet any issues when doing the changes, feel free to ask.

**Comment by yiheng-wang-nv** [comment]
This feature is implemented by @FaresAlMohamad in #482
