### ISSUE TITLE
Ask for the model architecture folder for wholeBody_ct_segmentation

### ISSUE THREAD

**Issue by EmanElrefai12** [Project-MONAI/model-zoo#485]
Hello, 

I am searching for the architecture of wholeBody_ct_segmentation in the repo but I can't find. I can find from other models like wholebrain threre is a network folder with the implementation of the model. Can you tell me if it's available or not and if it's available give me the link if it's possible.

**Comment by yiheng-wang-nv** [comment]
Hi @EmanElrefai12 , it's `SegResNet` and you can find details in:
https://github.com/Project-MONAI/model-zoo/blob/a4a08f8be6334cc9365d313f05af5674bf587381/models/wholeBody_ct_segmentation/configs/train.json#L25

The implementation of this network is in:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/networks/nets/segresnet.py

**Comment by tangy5** [comment]
The model is directly imported from MONAI package. For other models which are not defined in the MONAI Core, they will need to define as a separate component with script.

**Comment by yiheng-wang-nv** [comment]
Hi @EmanElrefai12 , do you have other questions? I will close this issue, and feel free to reopen it if needed.
