### ISSUE TITLE
Update `download_latest_bundle` to use monaihosting source

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#502]
It requires to use latest MONAI:
https://github.com/Project-MONAI/MONAI/pull/6963

This function works for our weekly blossom test on tensorrt.

**Comment by YanxuanLiu** [comment]
Added `pip install git+https://github.com/Project-MONAI/MONAI.git@dev` before running tests

**Comment by yiheng-wang-nv** [comment]
Verified that now our weekly tensorrt test works fine now on the latest bundle versions.
