### ISSUE TITLE
wholeBody_ct_segmentation model for DICOM input file

### ISSUE THREAD

**Issue by ytl0623** [Project-MONAI/model-zoo#508]
Hi, I was used wholeBody_ct_segmentation model to test custom clinical image.

But the format file is NIFITI (.nii), how can I inference the model with DICOM file format.

Is there any method to prove it.

Thanks in advance.

**Comment by diazandr3s** [comment]
Hi @ytl0623,

This is a good question.
I guess there are two options here:

- Use [monaibundle app ](https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/monaibundle#how-to-use-the-app) in MONAI Label and a DICOM Web server (Slicer, Orthanc) to run batch inference
- Convert DICOM images to NIfTI/NRRD and run batch inference as it is shown in the tutorial

Hope this helps,

**Comment by ArthurRomansini** [comment]
If you're using the model via a python script you can just pass the dicom directory to the preprocess like that:

```
CTDicomFolder = "./data/yourdicomfolder"
configPath = "./models/yourmodelhere/configs/inference.json"

config = ConfigParser()
config.read_config(configPath)
preprocessing = config.get_parsed_content("preprocessing")
data = preprocessing({'image': CTDicomFolder})
```
