### ISSUE TITLE
Downloading TorchScript file for ventricular_short_axis_3label produced NumPy file.    

### ISSUE THREAD

**Issue by MMelQin** [Project-MONAI/model-zoo#51]
I was trying to download and see what the model.ts file is like for the [ventricular_short_axis_3label](https://github.com/Project-MONAI/model-zoo/blob/dev/models/ventricular_short_axis_3label/large_files.yml).

I used `gdown"https://drive.google.com/uc?id=158RMzaGtgMgY1hCneDXmqCx7u046RbZE"`, but got a NumPy file `SC-N-2-3-0.npy`

BTW, `gdown` with the URL for the model.pt file did get the `model.pt` file.

**Comment by Nic-Ma** [comment]
Hi @MMelQin ,

Thanks for your interest here.
Please download the bundle from release, it contains all the data of a bundle:
https://github.com/Project-MONAI/model-zoo/releases/tag/hosting_storage_v1
We are building the web page for users to view-click-download.

Thanks.

**Comment by MMelQin** [comment]
Thanks @Nic-Ma.

I downloaded the model zip files from the link you provided above, and after unzip the file I can see in the models folder there are model.pt and model.ts.

However, model.ts is NOT a valid archive. Was it not saved correctly?

```
mqin@mingq-dt:~/src/model-zoo/bundles/ventricular_short_axis_3label/models$ unzip model.ts
Archive:  model.ts
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of model.ts or
        model.ts.zip, and cannot find model.ts.ZIP, period.
mqin@mingq-dt:~/src/model-zoo/bundles/ventricular_short_axis_3label/models$ 
```

And similarly, PyTorch complains too,
```
mqin@mingq-dt:~/src/monai-app-sdk$ python3
Python 3.7.5 (default, Feb 23 2021, 13:22:40) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.jit.load("/home/mqin/src/model-zoo/bundles/ventricular_short_axis_3label/models/model.ts")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mqin/.local/lib/python3.7/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
>>>
```

**Comment by Nic-Ma** [comment]
Hi @yiheng-wang-nv ,

Could you please help verify this issue? Maybe something wrong when doing zip?

Thanks in advance.

**Comment by yiheng-wang-nv** [comment]
Hi @MMelQin , thanks for reporting this issue. I double checked it, and the uploaded `model.ts` file is wrong. Hi @ericspod , could you please help to update the bundle with corrected `model.ts` file? Thanks!
On my side, I will enhance the premerged ci test to verify the provided `model.ts` file. The verification function should also include the mentioned pytorch version and solve the issue mentioned in: https://github.com/Project-MONAI/model-zoo/issues/50
