### ISSUE TITLE
Not compatible with 0.9.1* version

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/model-zoo#53]
Not able to run using monai 0.9.1.rc3 version.. (specially in case of deepedit which fails while running post inverse transform)

**Comment by SachidanandAlle** [comment]
May be other models also should need some verification against latest MetaTensor related changes...

**Comment by yiheng-wang-nv** [comment]
Hi @SachidanandAlle , in `configs/metadata.json`, library versions are included, and for this version of deepedit bundle, we can only ensure that it can work with monai v0.9.0.
For the metatensor based changed, we may need to add new supported versions.
cc @Nic-Ma

**Comment by Nic-Ma** [comment]
@yiheng-wang-nv , as MetaTensor is slightly breaking change, need to update new version bundles if the developer or user like to support MONAI 0.9.1.
CC @wyli 

Thanks.

**Comment by yiheng-wang-nv** [comment]
This issue has been resolved in: https://github.com/Project-MONAI/model-zoo/issues/180
