### ISSUE TITLE
Using Models from the Zoo on my custom datasets

### ISSUE THREAD

**Issue by AndromathArcanitus** [Project-MONAI/model-zoo#539]
Dear All,

I am new to MONAI and am hoping to use the model lung nodule ct detection from Model Zoo on my own dataset. I have already implemented my DataLoader. So, when I call it, the data is ready. But, when I see the configuration json file, the data is load through

"data_list_file_path": "$@bundle_root + '/LUNA16_datasplit/dataset_fold0.json'",
"dataset_dir": "/datasets/LUNA16_Images_resample",
"train_datalist": "$monai.data.load_decathlon_datalist(@data_list_file_path, is_segmentation=True, data_list_key='training', base_dir=@dataset_dir)",.

Can anyone provide any suggestions for my case? Should I save the data into a folder? But I don't know in what form the data should be saved. Thank you.

**Comment by KumoLiu** [comment]
Hi @AndromathArcanitus, you can change the data path in the configure file if you want to run bundle. Otherwise you could directly using the model weight in your pipeline. Thanks!
