### ISSUE TITLE
wholeBrainSeg_Large_UNEST_segmentation getting noise in the segmentation

### ISSUE THREAD

**Issue by kpbhat25** [Project-MONAI/model-zoo#556]
**Describe the bug**
I am getting other parts from the brain MRI being segmented.Tried with a simple Oasis(MRI) data.
![Screenshot (32)](https://github.com/Project-MONAI/model-zoo/assets/89582705/9bbc5149-dd62-47f0-913f-3bb45d291712)

What things should I change to get a cleaner segmentation, as mentioned in the paper

**Comment by KumoLiu** [comment]
Hi, @kpbhat25, thanks for your interest here.

Several things you can try. The first and most reasonable thing is to improve the performance of the network. Also, you can try to add some post-processing such as keeping the largest connected component or adding some intensity filter if you find that the noise is at some similar intensity level.

Hope it helps, thanks.
