### ISSUE TITLE
latest version of the model lung_nodule_ct_detection is not pushed to release..  

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/model-zoo#583]
[lung_nodule_ct_detection](https://github.com/Project-MONAI/model-zoo/blob/dev/models/lung_nodule_ct_detection/configs/inference.json#L99-L102)

```
            {
                "_target_": "EnsureChannelFirstd",
                "keys": "@image_key"
            },

```

is not reflecting in latest bundle package [lung_nodule_ct_detection_v0.5.9.zip](https://github.com/Project-MONAI/model-zoo/releases/download/hosting_storage_v1/lung_nodule_ct_detection_v0.5.9.zip)

**Comment by KumoLiu** [comment]
Hi @SachidanandAlle, the latest version is "0.6.5".
https://github.com/Project-MONAI/model-zoo/blob/de5a004a6f597ccf29a8ad1fe5146c1ddf8c1ffd/models/lung_nodule_ct_detection/configs/metadata.json#L5

You can download by:
```
python -m monai.bundle download "lung_nodule_ct_detection" --source monaihosting --bundle_dir .
```

Thanks.

**Comment by KumoLiu** [comment]
BTW, https://github.com/Project-MONAI/model-zoo/releases/tag/hosting_storage_v1 is no longer updated since https://github.com/Project-MONAI/model-zoo/pull/463.

**Comment by SachidanandAlle** [comment]
thanks 👍
