### ISSUE TITLE
Brats mri segmentation  training data cannot be downloaded

### ISSUE THREAD

**Issue by shihzenq** [Project-MONAI/model-zoo#607]
hello.
I used the Brats mri segmentation, but was unable to download the dataset.
![image](https://github.com/user-attachments/assets/bfd44f64-3cb6-4afa-8df9-863fe560649f)
skip https://www.med.upenn.edu/sbia/brats2018/data.html
![image](https://github.com/user-attachments/assets/71966085-39cc-4fc1-9bc0-581a0e5d3ec3)
![image](https://github.com/user-attachments/assets/f8709f84-bf28-47e5-961d-c88e715262bc)
I want to download to the dataset

thank you

**Comment by yiheng-wang-nv** [comment]
please reach out to the dataset owner, MONAI Model Zoo cannot distribute the dataset
