### ISSUE TITLE
New Brain Segmentation Bundle of UNEST Model with Vanderbilt U

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/model-zoo#64]
We will add a whole brain segmentation inference bundle with a new type of transformer-based segmentation 3D model.

The whole brain segmentation will contain 133 subclasses of T1w MRI images. 

Registration, segmentation pipeline will be included. 

This bundle construction will be collaborating with Vanderbilt University MASI lab.

**Comment by wyli** [comment]
closing via https://github.com/Project-MONAI/model-zoo/pull/84
