### ISSUE TITLE
Update large_files.yml for bundles

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#642]
some bundles use google drive to save large files, and the data are hosted in another place, thus we can update them

cc @KumoLiu @Nic-Ma

**Comment by ericspod** [comment]
These bundles reference gdrive in their `large_files.yml` URLs:

* brats_mri_axial_slices_generative_diffusion
* brats_mri_generative_diffusion
* brats_mri_segmentation
* breast_density_classification
* classification_template
* endoscopic_inbody_classification
* endoscopic_tool_segmentation
* lung_nodule_ct_detection
* maisi_ct_generative
* mednist_reg
* multi_organ_segmentation
* pancreas_ct_dints_segmentation
* pathology_nuclei_classification
* pathology_nuclei_segmentation_classification
* pathology_nuclick_annotation
* pathology_tumor_detection
* renalStructures_CECT_segmentation
* renalStructures_UNEST_segmentation
* spleen_ct_segmentation
* spleen_deepedit_annotation
* swin_unetr_btcv_segmentation
* ventricular_short_axis_3label
* vista3d
* wholeBody_ct_segmentation
* wholeBrainSeg_Large_UNEST_segmentation

We are also storing some model weights and data in the releases for this repo, so we should be consistent about where we choose to store such things. Unless Github objects the storage in releases would work for everything I'd have thought.

**Comment by yiheng-wang-nv** [comment]
Since we do some changes for the following bundles in: https://github.com/Project-MONAI/model-zoo/pull/620 I updated for them in a commit:

brats_mri_axial_slices_generative_diffusion
brats_mri_generative_diffusion
vista3d
pathology_nuclei_classification
pathology_nuclei_segmentation_classification
swin_unetr_btcv_segmentation

For other bundles, I will submit a PR to address that
