### ISSUE TITLE
New Bundle with Renal Substructures Segmentation Inference with UNEST model

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/model-zoo#69]
We are going to build a bundle for the kidney substructure segmentation with contrast enhanced CT images. 

This will be the first to release a model and an inference pipeline for renal structures segmentation with CTs, the model can be downloaded and used to the public. 

Will be the first public inference work on the task. 
![Screenshot from 2022-07-29 18-49-52](https://user-images.githubusercontent.com/58751975/181866417-106a2d01-e460-49b6-9551-eb001027dad9.png)

**Comment by numanai** [comment]
How can we download the pretrained weights? Thanks

**Comment by yiheng-wang-nv** [comment]
Hi @numanai , you can use: `https://github.com/Project-MONAI/MONAI/blob/dev/monai/bundle/scripts.py#L174` to download the bundle you interest.

**Comment by numanai** [comment]
Thank You!
