### ISSUE TITLE
flake8 5.0.1 issue

### ISSUE THREAD

**Issue by yiheng-wang-nv** [Project-MONAI/model-zoo#71]
flake8 releases 5.0.1 today, and it raises the following issue:
```
ModuleNotFoundError: No module named 'flake8.plugins.manager'
```
see: https://github.com/Project-MONAI/model-zoo/runs/7603793727?check_suite_focus=true#step:7:83

I think we may need to fix the version to 4.0.1 so far, and adjust it later.

**Comment by yiheng-wang-nv** [comment]
Hi @wyli , the issue also happens in `MONAI` repo (https://github.com/Project-MONAI/MONAI/runs/7604721904?check_suite_focus=true#step:7:188), what do you think?

**Comment by wyli** [comment]
thanks for reporting, I'm going to remove 'flake8-pyi', as we don't write any stub files at the moment.

**Comment by yiheng-wang-nv** [comment]
Thanks @wyli , I removed it and the issue is fixed.
