### ISSUE TITLE
In the project "lung_nodule_ct_detection", how to add the configuration for resuming training and loading a pre-trained model.pt?

### ISSUE THREAD

**Issue by dqy818** [Project-MONAI/model-zoo#712]
In the project "lung_nodule_ct_detection", how to add the configuration for resuming training and loading a pre-trained model.pt?

**Comment by yiheng-wang-nv** [comment]
Hi @dqy818 , I think you can refer to vista3d: https://github.com/Project-MONAI/model-zoo/blob/dev/models/vista3d/configs/train.json#L221
add a checkpoint loader

**Comment by dqy818** [comment]
thank you
