### ISSUE TITLE
VISTA-3D label.json file missing

### ISSUE THREAD

**Issue by nvahmadi** [Project-MONAI/model-zoo#716]
**Describe the bug**
Not really a bug, but missing information in VISTA-3D bundle. The README.md file states: ["We unified a global label index (docs/labels.json)"](https://github.com/Project-MONAI/model-zoo/tree/dev/models/vista3d#:~:text=We%20unified%20a%20global%20label%20index%20(docs/labels.json)), but this file cannot be found in bundle's subfolder "docs".

Could someone please add the labels.json file? Thanks in advance! :)

**Comment by KumoLiu** [comment]
Hi @nvahmadi, the file will be downloaded automatically when you download the bundle, as it is stored within the large file.
You can find it here:
https://github.com/Project-MONAI/model-zoo/blob/dev/models/vista3d/large_files.yml#L6

**Comment by nvahmadi** [comment]
Ah, apologies, I was looking for that file in the GitHub repo. Indeed, when I download the bundle, the file does show up. Thanks for the quick response. :)
