### ISSUE TITLE
Breaking Changes due to MetaTensor

### ISSUE THREAD

**Issue by vikashg** [Project-MONAI/model-zoo#73]
**Describe the bug**
Due to the the incorporation of MetaTensor there are breaking changes in the model zoo format on certain transforms `AddChannel`. There  is an appropriate documentation for the reason of the error

**To Reproduce**
1. git clone the monai repo
2. Install using pip install -e '.[all]'
3. Run using the following command
`python -m monai.bundle run training --meta_file ../model-zoo/models/spleen_ct_segmentation/configs/metadata.json --config_file ../model-zoo/models/spleen_ct_segmentation/configs/train.json  --logging_file ../model-zoo/models/spleen_ct_segmentation/configs/logging.conf `

**Additional context**
The metadata.json file includes the monai version compatibility but I think that is wrong. Maybe it should be rolled back to 0.8 for now and once the configs are updated with the new transforms we can switch it back to 0.9.0

**Comment by vikashg** [comment]
I just changed the monai version to 0.8.0 in the metadata.json file for the spleen_ct_segmentation, but I get the same errors. That tells me that we do not have a version compatibility check in the monai.bundle run function.

**Comment by Nic-Ma** [comment]
Hi @vikashg ,

Thanks for your feedback, we don't have check in the `bundle run` function so far.
I didn't see the `AddChannel` transform in the latest spleen bundle now:
https://github.com/Project-MONAI/model-zoo/blob/dev/models/spleen_ct_segmentation/configs/inference.json#L41
Could you please help take a look and try again?

Thanks in advance.

**Comment by vikashg** [comment]
Hi @Nic-Ma, 
Thanks I am working on it now. BTW I tried the following 
1. roll back monai to version 0.8.1 
2. install `pip install -e '.[all]'`
Now when I run ` python -m monai.bundle run training --meta_file ../model-zoo/models/spleen_ct_segmentation/configs/metadata.json --config_file ../model-zoo/models/spleen_ct_segmentation/configs/train.json  --logging_file ../model-zoo/models/spleen_ct_segmentation/configs/logging.conf `
I get the following error 
```
/home/gupta/anaconda3/envs/monai-deploy4/bin/python: No module named monai.bundle.__main__; 'monai.bundle' is a package and cannot be directly executed
```
So, seems like `monai.bundle run` was not working on 0.8.1 
Another follow up, if I do a `pip install monai` can I still use `python -m monai.bundle run ... ` because it seems like this functionality is only available when I build the code from source.

**Comment by wyli** [comment]
have you tried running both `pip uninstall monai` and `pip uninstall monai-weekly` a few times before pip install, sometimes the previous versions of the packages are not uninstalled properly

**Comment by vikashg** [comment]
Hi @wyli I did uninstall monai but I didnt do `pip uninstall monai-weekly` I will do that.

**Comment by MMelQin** [comment]
> Hi @wyli I did uninstall monai but I didnt do `pip uninstall monai-weekly` I will do that.

There is no monai.bundle before monai v0.9.0, and monai-weekly gets the latest dev version newer than 0.9.1 release.

**Comment by yiheng-wang-nv** [comment]
Hi @vikashg , so far is the issue solved? It seems this ticket can be closed.

**Comment by vikashg** [comment]
Yes I agree.
