### ISSUE TITLE
spleen_ct_segmentation: Evaluation should not save images for FL

### ISSUE THREAD

**Issue by holgerroth** [Project-MONAI/model-zoo#90]
**Describe the bug**
Current evaluation file in https://github.com/holgerroth/model-zoo/blob/dev/models/spleen_ct_segmentation/configs/evaluate.json
saves images. 

**To Reproduce**
Run evaluation of bundle

**Expected behavior**
Saving images is not desired in FL were we only want to report back the metric. 

**Screenshots**
n/a

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
================================
Printing MONAI config...
================================
MONAI version: 0.9.0
Numpy version: 1.23.1
Pytorch version: 1.12.1+cu102
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: af0e0e9f757558d144b655c63afcea3a4e0a06f5
MONAI __file__: /home/hroth/Code2/nvflare/monai-fl/integration/monai/nvflare_monai/lib/python3.8/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 4.0.1
scikit-image version: NOT INSTALLED or UNKNOWN VERSION.
Pillow version: 9.2.0
Tensorboard version: 2.9.0
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: NOT INSTALLED or UNKNOWN VERSION.
tqdm version: 4.64.0
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: 5.9.1
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.4 LTS
Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.29
Processor: x86_64
Machine: x86_64
Python version: 3.8.10
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 6
Num logical CPUs: 12
Num usable CPUs: 12
CPU usage (%): [16.3, 10.1, 10.0, 29.1, 12.3, 9.9, 10.1, 9.0, 11.1, 10.1, 13.6, 98.8]
CPU freq. (MHz): 1207
Load avg. in last 1, 5, 15 mins (%): [5.8, 7.9, 8.4]
Disk usage (%): 73.9
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 94.0
Available memory (GB): 84.6
Used memory (GB): 8.3

================================
Printing GPU config...
================================
Num GPUs: 2
Has CUDA: True
CUDA version: 10.2
cuDNN enabled: True
cuDNN version: 7605
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70']
GPU 0 Name: NVIDIA TITAN Xp COLLECTORS EDITION
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 30
GPU 0 Total memory (GB): 11.9
GPU 0 CUDA capability (maj.min): 6.1
GPU 1 Name: NVIDIA TITAN Xp COLLECTORS EDITION
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 30
GPU 1 Total memory (GB): 11.9
GPU 1 CUDA capability (maj.min): 6.1
```

**Additional context**
n/a

**Comment by Nic-Ma** [comment]
Hi @wyli @ericspod ,

Should we consider to remove the `SaveImage` logic in all the existing bundles?
@holgerroth I feel maybe we need more strong method to skip saving if the FL logic, we can't every bundle doesn't save anything during evaluation in the future?

Thanks.

**Comment by ericspod** [comment]
The intent of these scripts was to define a self-contained program that the users could run to get their results from the network. For these to be useful for both inference on the command line and be used in other contexts we have to have scripts that we can add saving to or some way of filtering out unwanted transforms when used in certain contexts. This was what I did with the deploy code where I would filter out saving and other transforms. What we could do in the inference scripts instead is break up the list of transforms into a load and regularise list plus a save list which will have the `SaveImage` transform, then the compose created to run inference would add these two together. In an FL context the second list can be overridden to be empty to remove that transform.

**Comment by Nic-Ma** [comment]
Hi @ericspod ,

Could you please help share the link of your deploy code solution?
Then maybe we can discuss more on @holgerroth 's FL problem.

Thanks in advance.

**Comment by ericspod** [comment]
The current implementation uses [this function](https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/2526579872f95c5b68cbcb0454a0dbba887352d5/monai/deploy/operators/monai_bundle_inference_operator.py#L103) to do the filtering. It relies on implementation details of Compose but otherwise works for a lot of the bundles we'd want to use.
